[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.24'
evm_version = 'cancun'
gas_reports = ['*']
gas_reports_ignore = []
optimizer = true
optimizer_runs = 200
via-ir = true

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
sepolia = { key = "${ETHERSCAN_MAINNET_KEY}", chain = 11155111 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
